Implemented code to get details for the activities within a specific pipeline run
elastacloud/azure-carbon-scheduler pull request #18
Opened 2023-06-26 13:56 UTC by nsftwr

![image](https://github.com/elastacloud/azure-carbon-scheduler/assets/14138020/465155b4-7499-4b7b-93b4-8405be2c01db)

2023-06-26 16:50 UTC, dazfuller requested changes

2023-06-26 16:50 UTC, dazfuller commented on src/CarbonIntensityTime.DataFactory/Models/PipelineRun.cs
> +public class PipelineActivity
This needs moving into it's own ile

2023-06-26 16:50 UTC, dazfuller commented on src/CarbonIntensityTime.DataFactory/Models/PipelineRun.cs
> +    public object Input { get; init; }
What is this type? Check to see if the input can be transformed into a Dictionary

2023-06-26 16:50 UTC, dazfuller commented on src/CarbonIntensityTime.DataFactory/Models/PipelineRun.cs
> +    public IList<PipelineActivity> Activities { get; init; }
add ` = new();` to the end here to remove the nullability warnings

2023-06-26 16:50 UTC, dazfuller commented on src/CarbonIntensityTime.DataFactory/FactoryClient.cs
> +        var pipelineRuns = getPipelineRuns.Select(async pr => new PipelineRun
Need to make sure we're not going to encounter 429 issues here when potentially reading a lot of pipelines and activities

2023-06-26 16:50 UTC, dazfuller commented on README.md
> +Note: If no ClientId and ClientSecret is specified, then AzureDefaultCredential will be used.
Suggest changing this to

> If no client id or secret is specified then the application will attempt to use the [AzureDefaultCredential](https://learn.microsoft.com/dotnet/api/azure.identity.defaultazurecredential) type which will check for Azure CLI, Visual Studio Code, etc... type of credentials first. If you are logged into a tenant other than the one in which the Azure Data Factory instance exists then you may get an error when running the code.

2023-06-27 11:40 UTC, nsftwr commented on src/CarbonIntensityTime.DataFactory/FactoryClient.cs
> +        var pipelineRuns = getPipelineRuns.Select(async pr => new PipelineRun
we will need to review as part of the SDK migration

2023-07-06 11:29 UTC, dazfuller approved these changes

2023-07-06 11:29 UTC, merged